In [8]:
import pandas as pd

In [9]:
df = pd.read_csv('crime_rate_safety_analysis.csv')
df

,incident_id,year,month,day_of_week,season,time_of_day,country,area_type,population_density_per_sqkm,crime_type,...,officers_assigned,investigation_duration_days,repeat_offender,gang_related,drug_related,cctv_coverage,lighting_condition,prior_incidents_same_location,safety_index,crime_resolved
0,CRM0000001,2022,7,Wednesday,Winter,Afternoon (12pm-6pm),Germany,Remote,16,Vandalism,...,2,46,No,No,No,No Coverage,Poorly Lit,3,62.8,No
1,CRM0000002,2024,4,Sunday,Autumn,Night (10pm-2am),Pakistan,Rural,252,Fraud,...,2,115,No,Yes,No,Partial Coverage,Partially Lit,1,50.7,No
2,CRM0000003,2023,2,Tuesday,Spring,Afternoon (12pm-6pm),USA,Rural,136,Assault,...,1,56,Yes,No,No,No Coverage,Well Lit,0,61.3,Yes
3,CRM0000004,2023,5,Saturday,Autumn,Evening (6pm-10pm),India,Rural,354,Robbery,...,4,44,Yes,Yes,No,Partial Coverage,Partially Lit,6,51.7,Yes
4,CRM0000005,2021,11,Saturday,Spring,Afternoon (12pm-6pm),Mexico,Urban,817,Burglary,...,5,111,No,Unknown,Yes,Partial Coverage,Partially Lit,2,52.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,CRM0009996,2024,11,Thursday,Winter,Morning (6am-12pm),Turkey,Suburban,327,Burglary,...,3,27,No,Yes,No,Partial Coverage,Well Lit,5,75.6,No
9996,CRM0009997,2024,4,Tuesday,Spring,Afternoon (12pm-6pm),Germany,Urban,1136,Burglary,...,5,41,No,No,No,Partial Coverage,Partially Lit,0,61.4,No
9997,CRM0009998,2024,11,Tuesday,Summer,Evening (6pm-10pm),France,Suburban,436,Assault,...,3,30,Unknown,No,Yes,Partial Coverage,Poorly Lit,1,65.1,Yes
9998,CRM0009999,2022,1,Friday,Summer,Evening (6pm-10pm),USA,Rural,169,Cybercrime,...,1,27,Unknown,No,No,Partial Coverage,Well Lit,2,77.5,No
9999,CRM0010000,2021,2,Thursday,Summer,Night (10pm-2am),Pakistan,Suburban,332,Vandalism,...,5,123,No,No,Unknown,Partial Coverage,Well Lit,1,51.4,No

In [10]:
df = df.drop(columns=['incident_id'])
df

,year,month,day_of_week,season,time_of_day,country,area_type,population_density_per_sqkm,crime_type,crime_severity_score,...,officers_assigned,investigation_duration_days,repeat_offender,gang_related,drug_related,cctv_coverage,lighting_condition,prior_incidents_same_location,safety_index,crime_resolved
0,2022,7,Wednesday,Winter,Afternoon (12pm-6pm),Germany,Remote,16,Vandalism,2.7,...,2,46,No,No,No,No Coverage,Poorly Lit,3,62.8,No
1,2024,4,Sunday,Autumn,Night (10pm-2am),Pakistan,Rural,252,Fraud,3.5,...,2,115,No,Yes,No,Partial Coverage,Partially Lit,1,50.7,No
2,2023,2,Tuesday,Spring,Afternoon (12pm-6pm),USA,Rural,136,Assault,5.7,...,1,56,Yes,No,No,No Coverage,Well Lit,0,61.3,Yes
3,2023,5,Saturday,Autumn,Evening (6pm-10pm),India,Rural,354,Robbery,7.0,...,4,44,Yes,Yes,No,Partial Coverage,Partially Lit,6,51.7,Yes
4,2021,11,Saturday,Spring,Afternoon (12pm-6pm),Mexico,Urban,817,Burglary,4.6,...,5,111,No,Unknown,Yes,Partial Coverage,Partially Lit,2,52.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2024,11,Thursday,Winter,Morning (6am-12pm),Turkey,Suburban,327,Burglary,5.2,...,3,27,No,Yes,No,Partial Coverage,Well Lit,5,75.6,No
9996,2024,4,Tuesday,Spring,Afternoon (12pm-6pm),Germany,Urban,1136,Burglary,7.0,...,5,41,No,No,No,Partial Coverage,Partially Lit,0,61.4,No
9997,2024,11,Tuesday,Summer,Evening (6pm-10pm),France,Suburban,436,Assault,5.2,...,3,30,Unknown,No,Yes,Partial Coverage,Poorly Lit,1,65.1,Yes
9998,2022,1,Friday,Summer,Evening (6pm-10pm),USA,Rural,169,Cybercrime,5.4,...,1,27,Unknown,No,No,Partial Coverage,Well Lit,2,77.5,No
9999,2021,2,Thursday,Summer,Night (10pm-2am),Pakistan,Suburban,332,Vandalism,2.3,...,5,123,No,No,Unknown,Partial Coverage,Well Lit,1,51.4,No

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 31 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   year                           10000 non-null  int64
 1   month                          10000 non-null  int64
 2   day_of_week                    10000 non-null  str
 3   season                         10000 non-null  str
 4   time_of_day                    10000 non-null  str
 5   country                        10000 non-null  str
 6   area_type                      10000 non-null  str
 7   population_density_per_sqkm    10000 non-null  int64
 8   crime_type                     10000 non-null  str
 9   crime_severity_score           10000 non-null  float64
 10  victim_count                   10000 non-null  int64
 11  victim_gender                  10000 non-null  str
 12  victim_age_group               10000 non-null  str
 13  injuries_reported              10000 non-null  int64
 14  fatalities                     10000 non-null  int64
 15  financial_loss_usd             10000 non-null  float64
 16  weapon_used                    6428 non-null   str
 17  suspect_status                 10000 non-null  str
 18  case_status                    10000 non-null  str
 19  reporting_method               10000 non-null  str
 20  response_time_minutes          10000 non-null  float64
 21  officers_assigned              10000 non-null  int64
 22  investigation_duration_days    10000 non-null  int64
 23  repeat_offender                10000 non-null  str
 24  gang_related                   10000 non-null  str
 25  drug_related                   10000 non-null  str
 26  cctv_coverage                  10000 non-null  str
 27  lighting_condition             10000 non-null  str
 28  prior_incidents_same_location  10000 non-null  int64
 29  safety_index                   10000 non-null  float64
 30  crime_resolved                 10000 non-null  str
dtypes: float64(4), int64(9), str(18)
memory usage: 2.4 MB

In [12]:
df.describe()

,year,month,population_density_per_sqkm,crime_severity_score,victim_count,injuries_reported,fatalities,financial_loss_usd,response_time_minutes,officers_assigned,investigation_duration_days,prior_incidents_same_location,safety_index
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,2022.147400,6.424900,1160.081000,5.679030,1.699600,0.905300,0.098900,2071.895031,35.751240,3.264600,53.709400,2.493200,54.197370
std,1.342182,3.434958,1777.794577,1.939029,1.029983,1.555691,0.437422,11201.130428,28.182986,1.864279,70.789713,1.582721,16.930764
min,2020.000000,1.000000,3.000000,1.000000,1.000000,0.000000,0.000000,2.080000,2.000000,1.000000,1.000000,0.000000,15.300000
25%,2021.000000,3.000000,123.000000,4.200000,1.000000,0.000000,0.000000,84.557500,17.400000,2.000000,16.000000,1.000000,40.400000
50%,2022.000000,6.000000,460.000000,5.700000,1.000000,0.000000,0.000000,250.570000,28.100000,3.000000,32.000000,2.000000,54.300000
75%,2023.000000,9.000000,1466.000000,7.100000,2.000000,2.000000,0.000000,921.590000,44.900000,4.000000,64.000000,3.000000,67.900000
max,2024.000000,12.000000,30210.000000,10.000000,5.000000,9.000000,3.000000,492775.010000,240.000000,10.000000,1500.000000,10.000000,93.700000

# 1. Verificar uso de memória

In [13]:
df.memory_usage(deep=True)

Index                               132
year                              80000
month                             80000
day_of_week                      561536
season                           550000
time_of_day                      671172
country                          552601
area_type                        549734
population_density_per_sqkm       80000
crime_type                       573263
crime_severity_score              80000
victim_count                      80000
victim_gender                    540131
victim_age_group                 540632
injuries_reported                 80000
fatalities                        80000
financial_loss_usd                80000
weapon_used                      475685
suspect_status                   590662
case_status                      638574
reporting_method                 629984
response_time_minutes             80000
officers_assigned                 80000
investigation_duration_days       80000
repeat_offender                  519697
gang_related                     517665
drug_related                     518877
cctv_coverage                    628285
lighting_condition               593035
prior_incidents_same_location     80000
safety_index                      80000
crime_resolved                   512957
dtype: int64

# 2. Verificar os tipos de dados

In [14]:
df.dtypes

year                               int64
month                              int64
day_of_week                          str
season                               str
time_of_day                          str
country                              str
area_type                            str
population_density_per_sqkm        int64
crime_type                           str
crime_severity_score             float64
victim_count                       int64
victim_gender                        str
victim_age_group                     str
injuries_reported                  int64
fatalities                         int64
financial_loss_usd               float64
weapon_used                          str
suspect_status                       str
case_status                          str
reporting_method                     str
response_time_minutes            float64
officers_assigned                  int64
investigation_duration_days        int64
repeat_offender                      str
gang_related                         str
drug_related                         str
cctv_coverage                        str
lighting_condition                   str
prior_incidents_same_location      int64
safety_index                     float64
crime_resolved                       str
dtype: object

In [15]:
df.memory_usage(deep=True).sum() / 1024**2

np.float64(10.68556022644043)

In [16]:
for col in df.columns:
    print('=' * 50)
    print(f'Coluna: {col}')
    print(f'Quantidade de valores únicos: {df[col].nunique()}')
    print(df[col].unique())

==================================================
Coluna: year
Quantidade de valores únicos: 5
[2022 2024 2023 2021 2020]
==================================================
Coluna: month
Quantidade de valores únicos: 12
[ 7  4  2  5 11  3  9  6  1 12  8 10]
==================================================
Coluna: day_of_week
Quantidade de valores únicos: 7
<StringArray>
['Wednesday', 'Sunday', 'Tuesday', 'Saturday', 'Monday', 'Thursday', 'Friday']
Length: 7, dtype: str
==================================================
Coluna: season
Quantidade de valores únicos: 4
<StringArray>
['Winter', 'Autumn', 'Spring', 'Summer']
Length: 4, dtype: str
==================================================
Coluna: time_of_day
Quantidade de valores únicos: 5
<StringArray>
['Afternoon (12pm-6pm)',     'Night (10pm-2am)',   'Evening (6pm-10pm)',
   'Morning (6am-12pm)', 'Late Night (2am-6am)']
Length: 5, dtype: str
==================================================
Coluna: country
Quantidade de valores únicos: 15
<StringArray>
[     'Germany',     'Pakistan',          'USA',        'India',
       'Mexico',    'Australia',    'Indonesia',       'Brazil',
 'South Africa',      'Nigeria',       'Canada',           'UK',
        'Egypt',       'France',       'Turkey']
Length: 15, dtype: str
==================================================
Coluna: area_type
Quantidade de valores únicos: 4
<StringArray>
['Remote', 'Rural', 'Urban', 'Suburban']
Length: 4, dtype: str
==================================================
Coluna: population_density_per_sqkm
Quantidade de valores únicos: 3230
[  16  252  136 ... 4242 2610 5644]
==================================================
Coluna: crime_type
Quantidade de valores únicos: 15
<StringArray>
[        'Vandalism',             'Fraud',           'Assault',
           'Robbery',          'Burglary',             'Theft',
        'Cybercrime',            'Murder',    'Sexual Assault',
        'Kidnapping', 'Domestic Violence',      'Drug Offense',
             'Arson',         'Extortion',       'Trafficking']
Length: 15, dtype: str
==================================================
Coluna: crime_severity_score
Quantidade de valores únicos: 91
[ 2.7  3.5  5.7  7.   4.6  2.5  3.2  8.6  4.2  2.6  7.4  7.5  8.8  6.2
  7.1  3.8  4.4  6.9  9.9  5.4  4.1  5.2  8.1  4.5  3.9  5.5  8.4  6.4
  5.   3.1  4.7  4.8  6.7  7.6  8.3  5.3  9.   3.4  2.2  7.3  3.   9.8
  4.   1.7  7.2  4.3  7.7  9.4  2.1  5.6  2.3  4.9  5.8  6.1  5.9  6.6
  6.5  3.3  2.8  3.6  3.7  6.8  8.9  9.7  7.9  1.2  2.9  8.7  2.4  6.
 10.   8.   9.3  9.2  9.5  8.5  5.1  6.3  1.4  1.3  1.5  1.8  7.8  1.1
  2.   8.2  9.1  1.9  1.   9.6  1.6]
==================================================
Coluna: victim_count
Quantidade de valores únicos: 5
[3 1 2 5 4]
==================================================
Coluna: victim_gender
Quantidade de valores únicos: 3
<StringArray>
['Female', 'Male', 'Unknown']
Length: 3, dtype: str
==================================================
Coluna: victim_age_group
Quantidade de valores únicos: 7
<StringArray>
['65+', '26-35', '18-25', '36-45', '46-55', '56-65', 'Under 18']
Length: 7, dtype: str
==================================================
Coluna: injuries_reported
Quantidade de valores únicos: 10
[0 1 3 2 5 4 9 8 6 7]
==================================================
Coluna: fatalities
Quantidade de valores únicos: 4
[0 1 3 2]
==================================================
Coluna: financial_loss_usd
Quantidade de valores únicos: 9420
[  114.41 19729.14   134.53 ...  1655.94   139.39 10061.92]
==================================================
Coluna: weapon_used
Quantidade de valores únicos: 6
<StringArray>
['Firearm', 'Knife', 'Unknown', nan, 'Vehicle', 'Blunt Object', 'Chemical']
Length: 7, dtype: str
==================================================
Coluna: suspect_status
Quantidade de valores únicos: 6
<StringArray>
[           'Arrested',           'Acquitted', 'Under Investigation',
             'Unknown',            'At Large',           'Convicted']
Length: 6, dtype: str
==================================================
Coluna: case_status
Quantidade de valores únicos: 5
<StringArray>
['Closed - Unsolved',   'Closed - Solved',     'Open - Active',
  'Open - Cold Case',     'Pending Trial']
Length: 5, dtype: str
==================================================
Coluna: reporting_method
Quantidade de valores únicos: 5
<StringArray>
[  'Emergency Call',   'Police Station',    'Anonymous Tip',
    'Online Portal', 'Community Report']
Length: 5, dtype: str
==================================================
Coluna: response_time_minutes
Quantidade de valores únicos: 1226
[ 23.5  31.8  72.4 ... 147.7  94.1 103.1]
==================================================
Coluna: officers_assigned
Quantidade de valores únicos: 8
[ 2  1  4  5  3  6 10  8]
==================================================
Coluna: investigation_duration_days
Quantidade de valores únicos: 391
[  46  115   56   44  111   31   48   20   33   21    8   24   67    9
   54   89  139   19   68   18   16   22   51   15   23   13   35   75
  168   49   42   17   30   37   52   43    3   36    2  238   70   14
  306    7  124   72   91   74   26   55   32   12   29   84  103    5
  184   85   39  101    6   97  343  166   10  123   27  108   11   77
   50   73   95  318   47   63   28  112    4   45   61  107  283  105
   80   78  260   66   34   86  240  137    1   69  403  162   60  479
   41   90   92  121  266   93  250  187  167  161   38  141  157   76
  150  421   62  295   59  106  127   57  373   40  125  114  236  122
  808  118   58  119   81   53   99  243  146  200  186  171  473  475
  109  253  235   64  297  179  212  135  129  214   71   82   25  152
  530  113  492  117   83  153  342   98   79   87  322  110  265  133
  100  180  170  225  351  177   96  229  136  386  205  218  191  156
  149  465  138  280  172  143  234  719  128  120   94  300   88  346
  155  178  104  173  134  202  151  145  182  102  193  116  175  174
  393  126   65  597  273  132  209  140  282  377  359  176  313  181
  163  381  228  154  165  201  190  344  207  278  426  255  195  353
  142  242  566  371  254  130  148  531  357  249  231  199  223  144
  224  131  298  257  219  220  330  258  159  348  244  541  226  192
  724  215  518  158  164  261  241  287  338  591  397  221  307  305
  147  276  765  375  272  211  797  208  169  303  573  217  394  237
  605  204  379  325  194  312  460  667  203  264  213  340  327  267
  270  198  239  412  901  410  292  183  485  326  652  247  319  439
  299  720  262  402  334  189  551  572  309  227  196  816  336  328
  364  274  396  782  197  365  246  216  407  286  626  417  317  973
  659  665  268  612  245  296  188  311  427  438  499  233  263  288
  804  339 1500  310  408  281  424  600  160  486  522  185  582  279
  398  210  374  367  819  269  290  252  434  230  251  387  277]
==================================================
Coluna: repeat_offender
Quantidade de valores únicos: 3
<StringArray>
['No', 'Yes', 'Unknown']
Length: 3, dtype: str
==================================================
Coluna: gang_related
Quantidade de valores únicos: 3
<StringArray>
['No', 'Yes', 'Unknown']
Length: 3, dtype: str
==================================================
Coluna: drug_related
Quantidade de valores únicos: 3
<StringArray>
['No', 'Yes', 'Unknown']
Length: 3, dtype: str
==================================================
Coluna: cctv_coverage
Quantidade de valores únicos: 3
<StringArray>
['No Coverage', 'Partial Coverage', 'Full Coverage']
Length: 3, dtype: str
==================================================
Coluna: lighting_condition
Quantidade de valores únicos: 4
<StringArray>
['Poorly Lit', 'Partially Lit', 'Well Lit', 'No Lighting']
Length: 4, dtype: str
==================================================
Coluna: prior_incidents_same_location
Quantidade de valores únicos: 11
[ 3  1  0  6  2  4  5  7  8 10  9]
==================================================
Coluna: safety_index
Quantidade de valores únicos: 748
[62.8 50.7 61.3 51.7 52.  68.2 56.9 59.3 32.5 34.  66.6 56.2 37.4 46.3
 48.9 59.2 38.7 23.8 79.3 90.2 33.9 47.3 66.1 44.9 48.6 83.2 53.5 65.7
 57.5 63.6 81.2 41.4 59.5 36.9 72.5 63.7 45.7 22.7 54.1 77.3 36.  53.7
 39.2 64.1 55.  48.5 39.7 38.4 68.8 59.8 62.9 33.7 52.9 60.7 77.2 62.2
 32.4 60.2 84.8 47.  76.5 29.9 34.8 81.1 47.2 51.4 46.2 71.  74.7 70.2
 43.1 75.1 51.8 18.  73.  17.6 55.8 80.1 68.1 65.9 49.6 48.1 47.5 54.2
 57.2 58.4 42.4 67.3 44.4 55.4 79.5 39.4 62.3 27.7 57.9 75.9 32.1 32.9
 43.6 31.8 16.  75.2 57.4 61.7 69.8 40.4 38.2 70.8 77.9 74.4 30.4 50.8
 59.4 32.8 67.6 49.2 58.  29.6 49.9 27.6 46.6 31.4 70.1 92.5 34.6 64.6
 75.6 38.9 72.7 66.8 80.8 65.8 47.7 89.9 40.7 35.  49.8 64.4 32.6 70.4
 44.2 80.3 69.2 34.2 58.9 69.7 50.9 40.6 80.9 64.9 46.5 33.  52.5 57.6
 61.9 51.6 51.1 63.1 31.9 74.5 15.7 60.6 26.3 61.2 57.8 76.2 49.7 59.7
 20.9 24.8 55.3 56.5 45.8 69.  53.4 63.  38.  15.4 53.6 81.3 37.  19.7
 64.  79.8 37.3 67.7 55.5 20.4 34.3 30.6 45.3 34.5 71.5 59.6 43.2 71.8
 48.2 74.  28.  84.9 51.2 84.6 30.5 77.  78.1 37.2 24.6 46.7 33.4 83.8
 26.7 28.7 56.4 58.2 73.9 71.2 83.5 57.3 56.  38.3 74.6 22.9 78.  33.5
 71.6 52.8 40.2 78.4 73.7 51.  42.6 77.8 74.3 49.4 39.3 57.7 15.8 63.9
 43.5 65.2 82.7 34.9 65.  85.  47.4 79.6 44.5 76.8 72.  71.4 30.  33.3
 18.4 39.8 55.1 35.3 63.8 41.3 34.1 29.7 67.8 27.4 66.3 39.1 44.1 40.8
 39.6 24.  31.  70.6 40.9 46.8 27.8 52.2 50.3 45.2 44.8 25.4 55.9 64.5
 61.6 42.2 84.4 43.  35.7 28.5 71.7 68.7 37.5 25.1 54.9 44.7 70.5 63.5
 54.  45.1 57.  78.7 28.9 33.2 42.3 43.4 57.1 40.5 19.5 67.1 30.3 77.6
 66.2 41.  61.4 36.3 50.  53.1 69.1 55.6 76.  30.1 81.4 39.9 18.9 51.9
 53.8 35.6 62.7 73.4 71.9 60.1 36.4 69.4 31.7 75.  59.1 52.1 43.7 29.5
 89.2 75.5 44.3 69.6 37.9 65.5 23.1 82.8 45.6 66.7 19.9 77.7 52.3 91.4
 71.1 60.3 82.6 56.3 27.2 42.8 58.6 80.7 59.9 54.6 60.4 73.2 67.2 32.3
 20.6 80.  44.6 41.5 38.5 79.2 74.8 49.  47.9 24.4 55.2 19.6 30.9 28.6
 81.9 45.5 66.  47.6 46.  54.8 33.6 72.6 25.5 63.4 88.4 72.4 68.4 51.3
 45.  21.5 66.9 60.9 48.7 37.7 76.4 56.8 33.8 42.7 72.1 67.9 60.  76.9
 84.3 48.3 25.7 52.7 49.5 42.1 50.5 82.9 72.2 77.4 73.1 35.5 79.1 26.4
 81.5 79.4 65.6 71.3 68.6 32.  35.4 67.  78.2 69.5 25.2 34.4 36.5 49.3
 17.3 76.7 17.9 83.7 65.3 22.6 86.7 41.9 62.6 58.1 30.8 37.6 40.  38.6
 61.1 85.8 64.7 74.9 77.1 36.6 26.8 78.5 35.2 54.4 87.6 38.1 68.9 69.9
 89.4 51.5 36.8 29.  30.7 46.9 72.3 37.1 52.4 47.8 19.3 19.8 82.5 66.5
 70.7 41.8 29.4 50.6 72.8 41.1 64.2 46.4 63.3 76.3 29.3 50.4 67.4 35.1
 78.8 81.8 45.9 31.3 24.9 63.2 43.9 56.1 62.5 20.1 36.7 75.7 22.5 31.6
 72.9 61.8 70.3 54.7 78.3 85.9 33.1 53.3 34.7 82.  43.3 73.6 43.8 48.
 78.9 20.8 56.7 66.4 22.4 50.1 42.9 78.6 39.  35.9 40.3 81.6 48.4 31.5
 75.3 32.2 56.6 23.3 83.  24.3 87.3 48.8 88.5 30.2 62.4 80.2 42.5 64.3
 70.9 27.5 21.6 75.8 45.4 73.5 53.  82.4 55.7 73.3 53.2 92.7 81.7 79.7
 47.1 68.5 79.  59.  87.4 24.1 70.  24.2 40.1 41.6 39.5 58.7 52.6 83.9
 25.9 20.3 54.5 69.3 22.8 28.3 76.6 86.6 38.8 82.1 83.1 61.  85.4 89.7
 58.5 36.2 23.5 35.8 18.6 73.8 37.8 29.8 58.8 61.5 23.6 67.5 60.8 31.1
 80.5 76.1 26.  65.4 68.  68.3 49.1 36.1 58.3 60.5 92.2 21.1 84.7 23.4
 74.1 16.3 41.7 24.7 91.5 44.  62.1 81.  25.8 23.  90.  90.3 20.5 28.1
 90.9 84.1 21.8 53.9 25.3 77.5 28.2 22.  86.1 62.  29.1 88.1 79.9 88.8
 41.2 83.3 27.9 27.3 84.2 88.2 83.4 84.  22.3 87.8 93.4 83.6 46.1 27.
 65.1 20.2 93.2 21.4 32.7 29.2 25.6 89.1 31.2 23.2 64.8 80.4 23.7 75.4
 54.3 50.2 82.2 87.5 26.2 19.4 21.2 26.9 26.1 80.6 92.3 26.5 19.1 17.2
 89.5 17.4 42.  74.2 89.6 26.6 24.5 90.5 91.3 23.9 21.  91.2 16.1 21.3
 90.6 28.4 88.7 20.  85.5 88.6 22.2 19.  28.8 86.4 19.2 89.3 25.  85.2
 27.1 82.3 91.6 20.7 21.7 22.1 16.6 93.7 18.8 15.9 90.8 90.7 87.1 16.5
 86.2 18.7 84.5 86.5 18.1 15.3 87.2 18.5 18.3 16.8 21.9 16.7 86.8 87.
 16.9 17.7 91.8 85.6 85.7 18.2]
==================================================
Coluna: crime_resolved
Quantidade de valores únicos: 2
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

# 3. Otimizar números inteiros

In [17]:
df['year'] = df['year'].astype('int16')
df['month'] = df['month'].astype('int8')
df['victim_count'] = df['victim_count'].astype('int16')

In [18]:
df.memory_usage(deep=True).sum() / 1024**2

np.float64(10.504362106323242)

# 4. Converter colunas de texto para category

In [19]:
colunas_categoria = [
    'day_of_week',
    'season',
    'time_of_day',
    'country',
    'area_type',
    'crime_type',
    'victim_gender',
    'victim_age_group',
    'weapon_used',
    'suspect_status',
    'case_status',
    'reporting_method',
    'lighting_condition',
    'crime_resolved'
]
    
for col in colunas_categoria:
    df[col] = df[col].astype('category')

In [20]:
df.memory_usage(deep=True).sum() / 1024**2

np.float64(3.0324363708496094)

# 5. Otimizar números decimais

In [21]:
df['financial_loss_usd'] = df['financial_loss_usd'].astype('float32')

In [22]:
df.memory_usage(deep=True).sum() / 1024**2

np.float64(2.9942893981933594)

# 6. Criando outro arquivo otimizado

In [23]:
df.to_csv('crime_rate_safety_analysis_optimized.csv', index=False)

# 7. Analise entre algumas colunas:

#### Tipo de crime pelo horário do dia:

In [25]:
df.groupby('time_of_day')['crime_type'].value_counts()

time_of_day           crime_type
Afternoon (12pm-6pm)  Theft          314
                      Assault        247
                      Robbery        209
                      Burglary       204
                      Fraud          177
                                    ...
Night (10pm-2am)      Murder          93
                      Arson           46
                      Extortion       39
                      Kidnapping      34
                      Trafficking     27
Name: count, Length: 75, dtype: int64

### Crimes mais graves:

In [26]:
df.groupby('crime_type')['crime_severity_score'].mean()

crime_type
Arson                7.556831
Assault              6.515728
Burglary             5.469741
Cybercrime           4.501524
Domestic Violence    6.488550
Drug Offense         5.492140
Extortion            6.460119
Fraud                5.039583
Kidnapping           8.009877
Murder               9.022599
Robbery              7.495487
Sexual Assault       8.475955
Theft                3.472849
Trafficking          8.983516
Vandalism            2.516165
Name: crime_severity_score, dtype: float64

### Dia da semana × Crimes:

In [ ]:
df.groupby('day_of_week')['crime_type'].count().sort_values(ascending=False)

day_of_week
Monday       1154
Tuesday      1170
Thursday     1342
Wednesday    1366
Friday       1443
Sunday       1733
Saturday     1792
Name: crime_type, dtype: int64

### Estação do Ano mais perigosa:

In [33]:
df.groupby('season')['crime_type'].count().sort_values(ascending=False)

season
Spring    2528
Winter    2528
Autumn    2503
Summer    2441
Name: crime_type, dtype: int64

### Gênero da vítima:

In [35]:
pd.crosstab(df['victim_gender'], df['crime_type'])

crime_type,Arson,Assault,Burglary,Cybercrime,Domestic Violence,Drug Offense,Extortion,Fraud,Kidnapping,Murder,Robbery,Sexual Assault,Theft,Trafficking,Vandalism
victim_gender,,,,,,,,,,,,,,,
Female,83,492,393,326,290,353,72,393,59,158,463,188,673,39,209
Male,87,620,511,358,330,420,83,515,89,176,589,228,880,46,294
Unknown,13,77,61,38,35,54,13,52,14,20,56,29,86,6,29